# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ff451bc651977a342210b6291d4da15d420df11cf950094914c7878e0534192e5847486483462b4faef48cd3bea0ead551f64aef22294b1d5e9d3f16c9e7ecc

test:
  secret_key_base: a15cf18840f331a5051b12dd652b7e7a78c02c2c9233afe9dc2f240ac226ab7c2ee82359d15224931387e1cff2ab2cd127383542fb54f5f95f8b184e8547fba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
